# Generated by Django 3.2.10 on 2021-12-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Store', '0003_auto_20211231_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
