# Generated by Django 3.0.5 on 2021-05-23 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('E_Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip_Code', models.CharField(max_length=10)),
                ('Phone', models.CharField(default='', max_length=12)),
                ('Secondary_Phone', models.CharField(blank=True, default='', max_length=12)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('ProductSubtotal', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='E_Store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Status', models.CharField(choices=[('Placed', 'Placed'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Placed', max_length=50)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Orders.Shipping_Address')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Orders', models.ManyToManyField(to='Orders.ProductOrdered')),
            ],
        ),
    ]
