# Generated by Django 3.0.5 on 2021-06-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productordered',
            name='Customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='Orders',
            field=models.ManyToManyField(related_name='order', to='Orders.ProductOrdered'),
        ),
    ]
